### PR TITLE
Pale Moon 27.1+ support

### PR DESCRIPTION
**Pull request by JustOff**
Based on [PMkit documentation draft v1.1](https://github.com/JustOff/pm27-sdk-addons/blob/master/PMkit.md), tested with [Pale Moon 27.1.0b1](http://www.palemoon.org/unstable/).

### CODE REVIEW

**Comment by pratikabu** [comment]
That's great. Will include this change in my next release. Thanks for the contribution.

**Comment by JustOff** [comment]
Thank you!

P.S. Your add-on was one of the reasons of my work aimed to provide the compatibility for extensions created using Mozilla Add-on SDK with Pale Moon.

**Comment by pratikabu** [comment]
Now since Firefox is moving to Webextensions, I cannot include this pull anymore as I'm going to remove Firefox specific code and will be generating all addons from Chrome codebase.

Sorry for that, I'll look into supporting other browsers sometime later.

**Comment by JustOff** [comment]
That's sad. Could you please consider releasing at least one intermediate Firefox (Pale Moon compatible) version based on Add-on SDK before moving to WebExtensions? You can host it directly on [Pale Moon Add-ons Site](https://addons.palemoon.org/) (I can assist you to create an account there if necessary).

**Comment by pratikabu** [comment]
I'll upload one on the Pale Moon addon site. Thanks for suggestion.

**Comment by pratikabu** [comment]
Sorry for the delay on this. I added the support for PaleMoon in my install.rdf file for [version 4.5.5](https://addons.cdn.mozilla.net/user-media/addons/_attachments/402816/scroll_to_top-4.5.5-fx.xpi). But it gives below error when I try to install it on PaleMoon browser.

image

Added below snippet in the .rdf file.

image

Any help?

**Comment by JustOff** [comment]
The error you get is because you missed the mandatory `maxVersion` line. The `minVersion` as of `25.0` also isn't correct here. It's better to literally follow [the guide](https://github.com/JustOff/pm27-sdk-addons/blob/master/PMkit.md) I referred above:
```
<em:targetApplication>
  <Description>
    <em:id>{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}</em:id>
    <em:minVersion>27.1.0b1</em:minVersion>
    <em:maxVersion>27.*</em:maxVersion>
  </Description>
</em:targetApplication>
```

**Comment by pratikabu** [comment]
Thanks for the suggestion. I changed it to support any version of the PaleMoon from 25th version. It seems to be working fine for 27.6.2. If it looks good to you, I'll upload this for PaleMoon moderation.

image

**Comment by JustOff** [comment]
1) Pale Moon 25.* and 26.* are not only unsupported anymore, but they can't load jpm-based addons, i.e. only [Scroll To Top 4.5.1](https://addons.mozilla.org/addon/scroll-to-top/versions/4.5.1.1-signed) is compatible with the old Pale Moon (but it does not compatible with Pale Moon 27.*).
2) Pale Moon add-ons site will not accept `<em:maxVersion>*</em:maxVersion>`, only `<em:maxVersion>27.*</em:maxVersion>`, [here](https://forum.palemoon.org/viewtopic.php?f=46&t=15225) is the explanation.

This is why `27.1.0b1` - `27.*` are preferred limits for Scroll To Top 4.5.5 for the current Pale Moon 27.*, as I already suggested above.

**Comment by pratikabu** [comment]
I understand your point. I'll update it as you've mentioned.
Earlier I thought I can keep * in the max version so that I need not to update the addon for any future PaleMoon release.

Thanks for your guidance.

**Comment by JustOff** [comment]
Thank you for your very useful add-on and efforts to support Pale Moon.

**Comment by pratikabu** [comment]
Hi, I've submitted the 4.5.5 version to PaleMoon moderation. Hopefully they should approve it.
Sent a PM to Lootyhoof.

**Comment by pratikabu** [comment]
Hi,

The addon is now live on PaleMoon site.

http://addons.palemoon.org/addon/scroll-to-top

I'll be closing this pull request now without actually pulling it. Thanks for your guidance & support.

Thanks
Pratik

**Pull request closed without merging**
